### ISSUE TITLE
Don't override existing version when using gradle's bintrayUplaod task

### ISSUE THREAD

**Issue by galvanu** [bintray/gradle-bintray-plugin#77] opened 2015-06-28 08:51 UTC
Hi,

I'm using the gradle plugin's task 'bintrayUpload' in order to publish a version of my project.
The problem is if I'm using a version that is already exists t overrides the files for the existing project.
My question is, there is any configuration which says 'don't override', so if I forget to change the version manually when running the 'bintrayUpload' task the task will fail.

Thanks.

**Comment by jerrywiltse** [comment] 2016-04-19 12:14
I actually notice that I get a conflict if I try to upload to a file that already exists.  I was coming here to request that the overwrite capability be added, because bintray support told me that this library doesn't currently expose the feature, although it is possible with the API.. 

I am using a maven repository, perhaps it is dependent upon the repo type.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':genius-updater:bintrayUpload'.
> Could not upload to "https://api.bintray.com/content/myfile/file-0.1.2.pom': HTTP/1.1 409 Conflict [message:Unable to upload files: An artifact with the path 'myfile/file-0.1.2.pom' already exists]

**Comment by eyalbe4** [comment] 2016-04-19 13:32
Hi @jerrywiltse,
The next plugin release will include the option to override uploaded files.

**Comment by jerrywiltse** [comment] 2016-04-23 17:01
Ok thanks!  

In the case a user leaves the default option of "Don't overwrite", I have the following suggestion. 

Set the exception handling to be such that multi-project builds don't stop when one module already exists and throws the conflict exception.  We would like it to continue to the next module, otherwise half the modules get uploaded, and the rest are missing.  Then, we have to go and manually delete stuff and repush.  It's very tedious.

There are certainly some cases when you want a failure to be fatal and hard stop.  So, i think an additional option would be warranted here to specify fail behavior.

**Comment by jerrywiltse** [comment] 2016-04-28 21:15
Can you please include the specifics of how that works?  Right now, our need is to only overwrite specific modules in a multiproject build. However, we don't want to delete the whole version or anything like that.  

Also, however it will work, is it using existing bintray API, or does it rely on upcoming new features in bintray API?

Regards,
Jerry

**Comment by eyalbe4** [comment] 2016-04-29 05:49
Hi @jerrywiltse,
The Plugin uses Bintray's Content Upload REST API for uploading files. The current plugin behavior is to block the upload of already published files. You can however upload the same again if it is not published (this is the default behavior of the rest API without the override flag).
In the next release of the plugin we plan to add the option to override the uploaded files of a version. The default will remain not to override. You will be able to set different override values for different modules.

**Comment by jerrywiltse** [comment] 2016-04-29 12:45
Does the current Bintray REST API permit an overwrite of published files?
Is the current limitation of the plugin due to the API, or simply due to
the way the plugin is written?

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by eyalbe4** [comment] 2016-04-29 13:28
@jerrywiltse, The Bintray REST API can receive a flag that indicates whether to overwrite. The default is not to overwrite. The current plugin code does not use this flag and therefore it does not allow overwriting published files. The next release of the plugin will expose an option to overwrite.

**Comment by jerrywiltse** [comment] 2016-04-29 14:51
Thanks Eyal!

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by eyalbe4** [comment] 2016-05-04 07:11
The code is [committed](https://github.com/bintray/gradle-bintray-plugin/commit/f4dcf73004835dc2f5f7ab26e67dbee58536314c). We'll update the README after the release.

**Comment by eyalbe4** [comment] 2016-06-22 09:41
@galvanu and @jerrywiltse,
This functionality is now released with 1.7. See the new *override* property in the *Plugin DSL* section as part of the README.
See the full release notes [here](https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin/1.7/view#release)

**Comment by solvingJ** [comment] 2016-09-18 07:32
Just tested, instead of overridding, it uploads new files: 
my-library-0.1.jar?override=1 
my-library-0.1.pom?override=1

**Comment by eyalbe4** [comment] 2016-09-21 13:39
Hi @solvingJ,
I'm not sure I understand your last comment. Can you please explain?

**Comment by solvingJ** [comment] 2016-09-21 19:42
Steps to reproduce: 
Publish a JAR file to a Maven repo on bintray with Gradle Plugin, for example using the "bintrayUpload" task.  

Then, In build.gradle , in the bintray{} closure, add the following: 

> override = true

Then, run the bintrayUpload task again.  Instead of overwriting the JAR file in the maven repo, the gradle plugin actually uploads a new file with extra text appended to the filename : "?override=1"

This appears to be a clear case where the code that sets the filename is extracting it from the URL, and since you added the feature, that extraction is failing to chop off the new query parameter of "override=1".  I will try to find the problem in the code.

**Comment by eyalbe4** [comment] 2016-09-21 20:49
Thanks @solvingJ.
Are you using version 1.7.1 of the plugin?

**Comment by solvingJ** [comment] 2016-09-23 02:30
Yes, 1.7.  Are you not able to reproduce?

**Comment by eyalbe4** [comment] 2016-09-23 03:40
@solvingJ,
Please use version 1.7.1 instead of 1.7 and let me know if the issue is resolved.

**Comment by tinnou** [comment] 2016-10-24 22:39
@eyalbe4 Confirmed. Changed from 1.7 to 1.7.1 and it works.
The override flag works properly.

**Comment by eyalbe4** [comment] 2016-10-24 22:45
Thanks for confirming this works for you @tinnou.
I'm closing this issue.

**Closed by eyalbe4** 2016-10-24 22:45 UTC

**Comment by xjliao** [comment] 2017-10-17 02:40
1.7.3,still there even though add "override=true"
