### ISSUE TITLE
Does maven sync really sync? Is this plugin maintained?

### ISSUE THREAD

**Issue by jnizet** [bintray/gradle-bintray-plugin#126] opened 2016-06-11 07:06 UTC
Here is what I have in my root project:

```
subprojects { subProject ->
    // ...
    apply plugin : 'com.jfrog.bintray'

    // ...
    bintray {
        user = 'ninjasquad'
        key = rootProject.findProperty('bintray.key')
        publications = ['mavenJava']
        publish = true
        pkg {
            repo = 'maven'
            name = subProject.name
            desc = subProject.description
            websiteUrl = 'http://dbsetup.ninja-squad.com'
            issueTrackerUrl = 'https://github.com/Ninja-Squad/DbSetup/issues'
            vcsUrl = 'https://github.com/Ninja-Squad/DbSetup/'
            licenses = ['MIT']
            version {
                gpg {
                    sign = true
                    passphrase = rootProject.findProperty('signing.password')
                }
                mavenCentralSync {
                    sync = true
                    user = rootProject.findProperty('sonatypeUserName')
                    password = rootProject.findProperty('sonatypePassword')
                }
            }
        }
    }
}
```

The two packages in bintray are configured to be synced with jcenter. I have set my signing key in the maven repo configuration.

I'm using the latest version of gradle (2.13) and the latest version of this plugin (1.6). Yet I've met several problems:

- my first attempt at using bintrayUpload failed at publishing the new version, despite the fact that publish is true. So I had to publish manually, using the web app.
- in that same attempt, jar files were uploaded, but signatures were not. I tried to sync with Maven central, but it failed, despite the fact that the maven repo has my signing key. That means bintray has my signing key, but doesn't sign the artefacts when syncing with Maven
- I thus deleted the version completely and tried again with the --info flag on the command line to try understanding why signature files weren't uploaded. That made the bintray upload hang.
- I thus removed the --info flag and tried again. Everything was uploaded, but the maven sync wasn't done, despite the sync flag being true, and the sonatype user and password being passed.
- I finally ended up syncing both packages with Maven central manually, which is exactly what I expected to be able to avoid by using bintray.

All in all, using bintray has been an unpleasant experience, filled with many bugs, holes in the documentation, mails to support.
I hope this will all be fixed, or at least explained in the plugin documentation. I don't have much hope though, seeing issues sitting here for several years without even a comment.

**Comment by eyalbe4** [comment] 2016-06-11 07:35
@jnizet, I'm sorry to hear that you were unable to use the Maven Central Sync functionality. We'd like to understand the cause of the issues you reported and would appreciate any feedback you may have about the documentation, so that it can be improved. To initiate this, will you be able to send an email to support@jfrog.com? It would be great if we can work together on this.

**Comment by jnizet** [comment] 2016-06-11 11:43
Hi @eyalbe4. I sent a detailed email to the support as requested.

Regarding the gradle plugin itself, in addition to the hang that shouldn't happen, to the signatures that should be uploaded or generated consistently, to the error messages that should be improved (error 400 is not sufficient), to the files that should be published consistently, what I would really like to have is, for each and every property that can be configured:

- what does it do exactly if the repo/package/version doesn't exist yet (for example: will a first upload create a repo or not. Will it create a package or not. Will it create a version or not)
- what does it do exactly if the repo/package/version already exists (for example: if I specify a description, will it change the description of the package, or leave the previous one? If I specify a sonatype user and password, will it just use it to do the sync, or will it also change the sonatype user in the repo configuration?)
- what are the prerequisites for the property to do its job. For example: is Maven sync only available if the repo is already synced with jcenter? Does it need the signing key to be configured in the repo? Will it sync it automatically with jcenter before doing the maven sync? 
- Is there any impact on the uploaded pom: for example, the project name, vcs url, etc. are already in the pom I upload. But does the plugin add the information to the pom if I specify it in the bintray config?

Those are questions that may look silly for you because you know how bintray and the plugin work (or are supposed to work). But for a stupid end-user like me, it's far from obvious. And a first release is painful:

- you have to configure the repo (sonatype user, signing key, etc.)
- then you have to upload 
- then you have to request for jcenter inclusion
- then either you sync with Maven central manually (eek), or delete everything and start again (eek)

**Comment by eyalbe4** [comment] 2016-06-11 16:28
Hi @jnizet,
We've just updated the README documentation and included most of your feedback. We'd appreciate your help improving the plugin by providing additional feedback you may have, or by contributing code through pull requests. We'll work with you through the support channel to resolve the issue you described.

**Comment by jnizet** [comment] 2016-06-11 17:20
PR submitted: #128. CLA signed, too.

**Comment by eyalbe4** [comment] 2016-09-05 07:47
@jnizet, with your permission, I'm closing this issue.

**Closed by eyalbe4** 2016-09-05 07:47 UTC
