### ISSUE TITLE
Jars and AARs in multi-module project uploaded to wrong directory

### ISSUE THREAD

**Issue by bensmiley** [bintray/gradle-bintray-plugin#199] opened 2017-11-10 13:36 UTC
I have the following in my `build.gradle`:

```
group = 'co.chatsdk.chatsdk'
version = '4.0.0'

ext {
    bintrayRepo = 'chat-sdk-android'
    bintrayName = 'chat-core'
    bintrayUserOrg = 'chat-sdk'

    publishedGroupId = 'co.chatsdk.chatsdk'
    libraryName = 'ChatSDKCore'
    artifact = 'chat-core'

    libraryDescription = 'Chat SDK Core library for Android'

    siteUrl = 'https://chatsdk.co'
    gitUrl = 'https://github.com/chat-sdk/chat-sdk-android.git'

    libraryVersion = '4.0.0'

    developerId = 'bensmiley'
    developerName = 'Ben Smiley-Andrews'
    developerEmail = 'ben@chatsdk.co'

    licenseName = 'Chat SDK License'
    licenseUrl = 'https://chatsdk.co/chat-sdk-license/'
    allLicenses = ['GPL-3.0']
}

apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
```

But when I run `bintrayUpload` the jar and aar files are uploaded to the wrong directory:

```
chat-core/
    /4.0.0/
       chat-core-4.0.0.pom
       chat-core-4.0.0.pom.asc
    /maven-metadata.xml

chat_sdk_core/
    /4.0.0/
        chat_sdk_core-4.0.0-sources.jar
        chat_sdk_core-4.0.0-sources.jar.asc
        chat_sdk_core-4.0.0.aar
        chat_sdk_core-4.0.0.aar.asc
```

Why is the module name used rather than the package name?

**Comment by cortinico** [comment] 2018-01-21 18:18
This is happening for me as well... I'm forced to rename the module to workaround this issue.

**Comment by leinardi** [comment] 2018-04-01 17:20
Still not answer for this issue? It is really annoying.

**Comment by AlexeiVainshtein** [comment] 2018-04-10 09:08
Thank you for reporting this @bensmiley . This issue occurs since inside the pom.xml the artifactId is configured with a different name then the project name. We are working on a fix for this issue so the artifactId will be populated from the pom if exists and if not will be taken from the project name.

**Comment by leleliu008** [comment] 2018-04-12 08:25
How to resolve this problem? I use [`kotlin-dsl`](https://github.com/gradle/kotlin-dsl) not groovy

**Comment by leleliu008** [comment] 2018-04-12 10:42
I have resolve this problem by add this config in build.gradle.kts of library:
`base {
    archivesBaseName = rootProject.name
}`

**Comment by AlexeiVainshtein** [comment] 2018-06-11 08:41
Hi All,

I just wanted to let you know that we have released new version of the Gradle Bintray plugin (1.8.1) that should fix this issue. Can you please try this with the new version and let us know the outcome? 

Thanks,

**Comment by leleliu008** [comment] 2018-06-13 05:42
@AlexeiVainshtein   version 1.8.1 work well, I've already confirmed it.

**Closed** 2018-06-14 08:38 UTC
