### ISSUE TITLE
Crashes with Gradle 2.4

### ISSUE THREAD

**Issue by gernotstarke** [bintray/gradle-bintray-plugin#73] opened 2015-05-07 08:46 UTC
see issue on gradle-forum:
https://discuss.gradle.org/t/gradle-2-4-fails-with-failed-to-notify-build-listener-where-gradle-2-3-successfully-builds/9515

**Comment by eyalbe4** [comment] 2015-05-08 14:59
René Groeschke from the core Gradle dev team managed to find the root cause of the issue and provided a workaround for it (thank you Rene!)
The details are available at:
https://discuss.gradle.org/t/gradle-2-4-fails-with-failed-to-notify-build-listener-where-gradle-2-3-successfully-builds/9515

I'm therefore closing this issue.

**Closed by eyalbe4** 2015-05-08 14:59 UTC
